### ISSUE TITLE
Passing iterable and non-iterable args to function

### ISSUE THREAD

**Issue by benweinberg89** [niedakh/pqdm#2]
* Parallel TQDM version:
0.1.0
* Python version:
3.6.5
* Operating System:
Mac OS 10.14.6

### Description
I have a function that takes multiple arguments but only iterates over one of them. How would I implement this?

### What I Did
I've had to re-write the function to take only the iterable as its argument but this is not ideal.

**Comment by niedakh** [comment]
This is a valid case. I will think about adding an extra parameter for "constant" arguments. Thank you for this report.

**Comment by pjbull** [comment]
We implemented this outside of what we passed to `tqdm` by just using `itertools.repeat`, which worked well. Would be convenient to have as part of the API though.

**Comment by dangercrow** [comment]
This feels outside of the scope of pqdm - you should probably be using `functools.partial` or something similar to apply your constant arguments

https://docs.python.org/3/library/functools.html#functools.partial

**Comment by LCWilliams** [comment]
I'm sorry, but I fail to see how this is outside the scope?

You're asking people to add additional complexity to their code when they want to simply pass one or more additional arguments to the called function besides just the iterable. The API should be doing nothing with it except forwarding them. 

Limiting people to an iterable only argument function is frankly ridiculous.
