### ISSUE TITLE
Allow control over which progress bars to show.

### ISSUE THREAD

**Issue by pjbull** [niedakh/pqdm#54]
* Parallel TQDM version: 0.1.0
* Python version: 3.6.10
* Operating System: macOS

### Description

I'm using this in a place where some users are confused by the additional "submitted" and "collected" progress bars. It would be great to be able to optionally hide them.

Happy to submit a PR if you would consider this feature!

**Comment by niedakh** [comment]
I thought about this and I'd guess that's basically what tqdm.contrib.concurrency does - I don't think this would be useful here, as one of the main reasons for the library is to see clearly what's happening - in big tasks queueuing up futures can take from tenths of minutes to hours, for smaller tasks tqdm.contrib.concurrency does its job.

I've decided to add a more explainable descriptions, perhaps those will make the messages more understandable: 
- submitting -> queueuing tasks
- processing -> processing tasks
- collected -> collecting results

**Comment by Evidlo** [comment]
Can we reopen this for consideration?  I actually prefer pqdm's interface, and the docs for `tqdm.contrib.concurrent` are pretty lacking.
